### ISSUE TITLE
Rename repo to `ClearWater-modules`?

### ISSUE THREAD

**Issue by aufdenkampe** [EcohydrologyTeam/ClearWater-modules-python#17]
Given that we have decided to advance these modules only in Python, can we shorten the name of the repo from `ClearWater-modules-python` to `ClearWater-modules`.  The longer name is a mouthful.

We would still keep `ClearWater-modules-cpp` as a repo, to archive that work if we wanted to revive it.

What do you think @TSteissberg, @kewalak, @imscw95, @xaviernogueira, @sjordan29, @jrutyna?

**Comment by aufdenkampe** [comment]
@xaviernogueira, @kewalak, and @imscw95, let's move toward this renaming sooner than later. 

I can rename the repo anytime, but the official name of the package is in the source directory (presently `src/clearwater_modules_python`), so one of you will need to do a `git mv` of that directory to rename to `src/clearwater_modules` then modify all your import statements to the following or similar:
```python
import clearwater_modules as cam
```

**Comment by xaviernogueira** [comment]
@aufdenkampe I don't have the privladges to rename the repo, but I can rename the package right nw

**Comment by xaviernogueira** [comment]
Closed w/ PR #33

**Comment by aufdenkampe** [comment]
I just renamed the repo. Github should do automated redirects of any references to the old URL, so nothing should break, but we'll want to slowing update our references to the name.
